version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      args:
        WORKDIR: $WORKDIR
    ports:
      - 3000:3000
    volumes:
      - "./frontend:/$WORKDIR"
    command: sh -c "cd unimark && npm run dev"
  backend:
    build:
      context: ./backend
    environment:
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/backend
