name: code_build
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "github-actions"
    branches:
      - main
    types:
      - completed
jobs:
  frontend-build:
    name: Frontend Build image
    env:
      SERVICE_NAME: unimark-app-frontend
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.frontend-buildx-cache
          key: ${{ runner.os }}-frontend-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-frontend-buildx-

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - uses: docker/build-push-action@v2
        id: build-image
        with:
          push: true
          file: frontend/Dockerfile
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.SERVICE_NAME }}:latest
          cache-from: type=local,src=/tmp/.frontend-buildx-cache
          cache-to: type=local,dest=/tmp/.frontend-buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.frontend-buildx-cache
          mv /tmp/.frontend-buildx-cache-new /tmp/.frontend-buildx-cache

  backend-build:
    name: Backend Build image
    env:
      SERVICE_NAME: unimark-app-backend
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.backend-buildx-cache
          key: ${{ runner.os }}-backend-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-backend-buildx-

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: ap-northeast-1

      - name: Add IP Address
        env:
          SECURITY_GROUP_ID: ${{ secrets.SECURITY_GROUP_ID }}
        run: |
          # Public IP (Github Actions)
          IP_ADDRESS=`curl ifconfig.io`

          # Add IP Address to Security Group Ingress
          aws ec2 authorize-security-group-ingress --group-id ${SECURITY_GROUP_ID} --protocol tcp --port 3306 --cidr "$IP_ADDRESS"/32

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - uses: docker/build-push-action@v2
        id: build-image
        with:
          push: true
          file: backend/Dockerfile
          context: ./backend
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.SERVICE_NAME }}:latest
          build-args: DATABASE_URL=${{ secrets.DATABASE_URL }}
          cache-from: type=local,src=/tmp/.backend-buildx-cache
          cache-to: type=local,dest=/tmp/.backend-buildx-cache-new,mode=max

      - name: Remove IP Address
        env:
          SECURITY_GROUP_ID: ${{ secrets.SECURITY_GROUP_ID }}
        if: ${{ always() }}
        run: |
          # Public IP (Github Actions)
          IP_ADDRESS=`curl ifconfig.io`

          # Remove IP Address 
          aws ec2 revoke-security-group-ingress --group-id ${SECURITY_GROUP_ID} --protocol tcp --port 3306 --cidr "$IP_ADDRESS"/32

      - name: Move cache
        run: |
          rm -rf /tmp/.backend-buildx-cache
          mv /tmp/.backend-buildx-cache-new /tmp/.backend-buildx-cache
