name: github-actions
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/unimark
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run lint
